package http

import (
	"context"

	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/gliedabrennung/messenger-core/internal/controller/http/middleware"
	"github.com/gliedabrennung/messenger-core/internal/messenger"
	"github.com/gliedabrennung/messenger-core/internal/pkg/api"
	"github.com/gliedabrennung/messenger-core/internal/usecase"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
	_ "github.com/gliedabrennung/messenger-core/docs" // This will be generated by swag
)

func SetupRouter(h *server.Hertz, authUseCase *usecase.AuthUseCase, msgUseCase *usecase.MessageUseCase, contactUseCase *usecase.ContactUseCase, jwtSecret string) {
	h.Use(api.CustomErrorHandler())
	h.NoRoute(func(ctx context.Context, c *app.RequestContext) {
		api.ErrorResponse(c, http.StatusNotFound,
			"NOT_FOUND",
			"Page not found",
			nil)
	})
	h.NoMethod(func(ctx context.Context, c *app.RequestContext) {
		api.ErrorResponse(c, http.StatusMethodNotAllowed,
			"METHOD_NOT_ALLOWED",
			"Method not allowed",
			nil)
	})

	authHandler := NewAuthHandler(authUseCase)
	msgHandler := NewMessageHandler(msgUseCase)
	contactHandler := NewContactHandler(contactUseCase)

	h.GET("/", ServeHome)
	h.GET("/health", func(ctx context.Context, c *app.RequestContext) {
		c.String(http.StatusOK, "ok")
	})

	auth := h.Group("/auth")
	auth.POST("/register", authHandler.Register)
	auth.POST("/login", authHandler.Login)

	h.GET("/ws", middleware.JWTAuth(jwtSecret), messenger.ServeWs)

	h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler))

	apiGroup := h.Group("/api", middleware.JWTAuth(jwtSecret))
	apiGroup.GET("/users", authHandler.GetAllUsers)
	apiGroup.GET("/messages", msgHandler.GetHistory)
	apiGroup.GET("/messages/unread", msgHandler.GetUnreadCounts)
	apiGroup.POST("/messages/upload", msgHandler.UploadAudio)

	apiGroup.POST("/contacts", contactHandler.AddContact)
	apiGroup.PATCH("/contacts/:id", contactHandler.AcceptContact)
	apiGroup.GET("/contacts", contactHandler.GetContacts)
	apiGroup.DELETE("/contacts/:id", contactHandler.RemoveContact)

	adminGroup := apiGroup.Group("/admin", middleware.RoleAuth(authUseCase, "admin"))
	adminGroup.DELETE("/users/:id", authHandler.DeleteUser)
}
