services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      scylla:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  scylla:
    image: scylladb/scylla:5.4.0
    ports:
      - "9042:9042"
    command: --smp 1 --memory 1G --developer-mode 1
    volumes:
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe keyspaces' $$(hostname -i)" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  postgres_data:
  scylla_data:
